# Generated by Django 5.1.1 on 2024-09-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
