# Generated by Django 5.1.1 on 2024-09-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0006_alter_messages_connected_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="money",
            field=models.CharField(default=5000, max_length=50),
        ),
        migrations.AddField(
            model_name="users",
            name="sword_level",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
