# Generated by Django 5.1.1 on 2024-09-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0007_users_money_users_sword_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="sword_level",
            field=models.IntegerField(default=0),
        ),
    ]
