# Generated by Django 5.1.1 on 2024-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0008_alter_users_sword_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="money",
            field=models.IntegerField(default=5000),
        ),
    ]
